version: '3.8'

services:

  catalogdb:
    image: mongo


  basketdb:
    image: redis:alpine


  discountdb:
    image: postgres:alpine


  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest


  rabbitmq:
    image: rabbitmq:3-management-alpine


  mongo_gui:
    image: mongoclient/mongoclient


  portainer:
    image: portainer/portainer-ce


  pgadmin:
    image: dpage/pgadmin4


#${DOCKER_REGISTRY-}catalogapi
#${DOCKER_REGISTRY-}basketapi

  catalog.api:
    image: ahmeds88/catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile


  basket.api:
    image: ahmeds88/basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile


  discount.api:
    image: ahmeds88/discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile


  discount.grpc:
    image: ahmeds88/discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile


  ordering.api:
    image: ahmeds88/orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/API/Ordering.API/Dockerfile


  ocelotapigw:
    image: ahmeds88/ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile

# ------------ ( Volumes ) ---------------



  shopping.aggregator:
    image: ahmeds88/shoppingaggregator
    build:
      context: .
      dockerfile: ApiGateways/Shopping.Aggregator/Dockerfile

  aspnetrunbasics:
    image: ahmeds88/aspnetrunbasics
    build:
      context: .
      dockerfile: WebApps/AspnetRunBasics/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:







