version: '3.8'

services:
  catalogdb:
    image: mongo

  
  mongo_gui:
    image: mongoclient/mongoclient


#${DOCKER_REGISTRY-}catalogapi
  catalog.api:
    image: ahmeds88/catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  mongo_data:
